name: Build EXE on PR

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt 2>nul || echo "No requirements.txt found"

    - name: Build EXE
      run: |
        echo "Running pyinstaller to build the executable..."
        echo "Current directory contents:"
        dir
        echo "Current working directory:"
        python -c "import os; print(os.getcwd())"
        cd D:\a\File-Organizer\File-Organizer
        pyinstaller --clean --log-level DEBUG FileOrganizer.spec
        echo "pyinstaller build completed."

    - name: List all files in dist directory
      run: |
        echo "Listing all files in dist directory and subdirectories:"
        if (Test-Path dist) {
          Get-ChildItem -Path dist -Recurse
        } else {
          echo "dist directory not found"
        }

    - name: Zip the package
      run: |
        echo "Checking if FileOrganizer.exe exists..."
        $exePath = Get-ChildItem -Path dist -Recurse -Filter FileOrganizer.exe | Select-Object -First 1 -ExpandProperty FullName
        if ($exePath) {
          echo "FileOrganizer.exe found at: $exePath"
          $distPath = Split-Path -Parent $exePath
          Compress-Archive -Path "$distPath\*" -DestinationPath dist\FileOrganizer.zip -Force
          echo "ZIP archive created."
        } else {
          Write-Error "FileOrganizer.exe not found in dist directory or its subdirectories"

    - name: Upload ZIP
      uses: actions/upload-artifact@v4
      with:
        name: FileOrganizer
        path: dist\FileOrganizer.zip
        retention-days: 1

  cleanup:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
    - name: Delete old artifacts
      run: |
       gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.expired == true) | .id' | xargs -I {} gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/{}