name: Build EXE on PR

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller FileOrganizer.spec

    - name: Zip the package
      run: |
        powershell Compress-Archive -Path dist/FileOrganizer.exe -DestinationPath dist/FileOrganizer.zip

    - name: Upload ZIP
      uses: actions/upload-artifact@v4
      with:
        name: FileOrganizer
        path: dist/FileOrganizer.zip
        retention-days: 1  # Automatically delete the artifact after 1 day

  cleanup:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
    - name: Delete old artifacts
      run: |
        gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.expired == true) | .id' | xargs -I {} gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/{}
